package Clases;


import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.security.InvalidParameterException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANDY ESCOBAR
 */
public class JF_MenuPrincipal extends javax.swing.JFrame {

    DFA dfa;
    String[] estados;
    private String OPTION;
   
    
    /**
     * Creates new form JF_MenuPrincipal
     */
    public JF_MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDirectorios();
       // updateRowHeight();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        lblMensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblAFD = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        pnlAFD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStates = new javax.swing.JTextField();
        txtAlfabeto = new javax.swing.JTextField();
        txtEstadosFinales = new javax.swing.JTextField();
        txtEstadoInicial = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCrearDFA = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnGenerar = new javax.swing.JButton();
        txtStatecount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        btnEvaluarCadena = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        cmbTextFile = new javax.swing.JComboBox<>();
        btnEvaluarArchivo = new javax.swing.JButton();
        ck_contentSubstring = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);

        barPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        lblAFD.setBackground(new java.awt.Color(204, 204, 204));
        lblAFD.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAFD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAFD.setText("AFD");
        lblAFD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAFDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barPanelLayout = new javax.swing.GroupLayout(barPanel);
        barPanel.setLayout(barPanelLayout);
        barPanelLayout.setHorizontalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1024, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barPanelLayout.setVerticalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.setLayout(new java.awt.CardLayout());

        pnlAFD.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Entradas");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Q");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Σ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("F");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("s");

        txtStates.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtStates.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStatesKeyReleased(evt);
            }
        });

        txtAlfabeto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEstadosFinales.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEstadoInicial.setEditable(false);
        txtEstadoInicial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnCrearDFA.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearDFA.setText("Crear DFA");
        btnCrearDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDFAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearDFA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearDFA)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Tabla de Transicion");

        btnGenerar.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtStatecount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStatecount.setText(" ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Entrada");

        txtEntrada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 102, 51));
        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEntradaKeyReleased(evt);
            }
        });

        btnEvaluarCadena.setBackground(new java.awt.Color(255, 255, 255));
        btnEvaluarCadena.setText("Evaluar");
        btnEvaluarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarCadenaActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblMensaje.setText("jLabel8");

        cmbTextFile.setBackground(new java.awt.Color(255, 255, 255));
        cmbTextFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEvaluarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        btnEvaluarArchivo.setText("Evaluar Archivo");
        btnEvaluarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarArchivoActionPerformed(evt);
            }
        });

        ck_contentSubstring.setBackground(new java.awt.Color(255, 255, 255));
        ck_contentSubstring.setText("Contiene SubString");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(ck_contentSubstring)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEntrada))
                        .addGap(18, 18, 18)
                        .addComponent(btnEvaluarCadena))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEvaluarArchivo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ck_contentSubstring))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEvaluarCadena)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluarArchivo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAFDLayout = new javax.swing.GroupLayout(pnlAFD);
        pnlAFD.setLayout(pnlAFDLayout);
        pnlAFDLayout.setHorizontalGroup(
            pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFDLayout.createSequentialGroup()
                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAFDLayout.createSequentialGroup()
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadosFinales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlfabeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlAFDLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEstadoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))))
                        .addGap(1, 1, 1)
                        .addComponent(txtStatecount, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAFDLayout.createSequentialGroup()
                        .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
        );
        pnlAFDLayout.setVerticalGroup(
            pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFDLayout.createSequentialGroup()
                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAFDLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtStatecount))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel3)
                                    .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel4)
                                    .addComponent(txtEstadosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAFDLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAFDLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(pnlAFD, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 72, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        //      printEstados();
        cargarEstadosToTabla();
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCrearDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDFAActionPerformed
        try{
            jTable1.clearSelection();
            getTransiciones();
            Manager_DFA manager_DFA=new Manager_DFA(new JsonFile("DFAs"));
            manager_DFA.addNewDFA("ANDY",true, dfa);
            jPanel3.setVisible(true);
            JOptionPane.showMessageDialog(null, "Tabla de transicion creada exitosamente");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null,"Existen algunas celda vacias porfavor rellene la tabla","Tabla de Trasicion",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCrearDFAActionPerformed

    private void txtStatesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStatesKeyReleased
        setEstados(txtStates.getText());
        txtStatecount.setText(String.valueOf(getEstados().length));
        txtEstadoInicial.setText(getEstadoInicial());
    }//GEN-LAST:event_txtStatesKeyReleased

    private void lblAFDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAFDMouseClicked
        selectBotonColor(lblAFD);
        changePanel(mainPanel, pnlAFD);
    }//GEN-LAST:event_lblAFDMouseClicked

    private void btnEvaluarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarArchivoActionPerformed
        evaluarArchivoTexto();
    }//GEN-LAST:event_btnEvaluarArchivoActionPerformed

    private void btnEvaluarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarCadenaActionPerformed
        evaluarEntrada();

    }//GEN-LAST:event_btnEvaluarCadenaActionPerformed

    private void txtEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyReleased
        lblMensaje.setVisible(false);
    }//GEN-LAST:event_txtEntradaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JF_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barPanel;
    private javax.swing.JButton btnCrearDFA;
    private javax.swing.JButton btnEvaluarArchivo;
    private javax.swing.JButton btnEvaluarCadena;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JCheckBox ck_contentSubstring;
    private javax.swing.JComboBox<String> cmbTextFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lblAFD;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlAFD;
    private javax.swing.JTextField txtAlfabeto;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtEstadoInicial;
    private javax.swing.JTextField txtEstadosFinales;
    private javax.swing.JLabel txtStatecount;
    private javax.swing.JTextField txtStates;
    // End of variables declaration//GEN-END:variables

     
    private void resetColorLateralButtons(){
        Color color=new Color(255,255,255);
        lblAFD.setBackground(color);
    }
    
    private void changePanel(JPanel parent,JPanel son){
        parent.removeAll();
        parent.add(son);
        parent.repaint();
        parent.revalidate();
    
    }
    private void selectBotonColor(JLabel lbl){
        lbl.setOpaque(true);
        resetColorLateralButtons();
        if(OPTION!=null&& OPTION.equals(lbl.getText())){
            OPTION=lbl.getText();
        }else{
            OPTION=lbl.getText();
            System.out.println("OPTION SELECTED: "+OPTION);
        }
        lbl.setBackground(new Color(204,204,204));
    }
    
    private void updateRowHeight(){
        for(int row=0;row<jTable1.getRowCount();row++){
            int rowHeight=jTable1.getRowHeight();
            for (int column = 0; column <jTable1.getColumnCount() ; column++) {
                Component comp=jTable1.prepareRenderer(jTable1.getCellRenderer(row, column), row, column);
                rowHeight=Math.max(rowHeight, comp.getPreferredSize().height);
            }
            jTable1.setRowHeight(row,rowHeight);
        }
    }
    
    private String[] to_array(String arr){
        return arr.split(",");
    }
    
    private String[] getEstados(){
        return estados;
    }
    
    private void setEstados(String string){
        estados=to_array(string);
    }
    private void printEstados(){
        for (String estado : getEstados()) {
            System.out.println(estado);
        }
    }
    
    private String[] getAlfabeto(){
        return txtAlfabeto.getText().split(",");
    }
    
    private String getEstadoInicial(){
        return getEstados()[0];
    }
    
    private void cargarEstadosToTabla(){
        DefaultTableModel modelo= new DefaultTableModel();
        String alfabeto[]=getAlfabeto();
        modelo.addColumn("STATE");
        for (String caracter : alfabeto) {
            modelo.addColumn(caracter);
        }
        Object rows[]= new Object[getAlfabeto().length+1];
        for (String estado : getEstados()) {
            modelo.addRow(new Object[]{estado});
        }      
        jTable1.setModel(modelo);
    }
    
    
    private ArrayList<Transicion> getTransiciones(){
        ArrayList<Transicion> transiciones=new ArrayList<>();
        int columnas=jTable1.getColumnCount();
        int filas=jTable1.getModel().getRowCount();
        for (int i = 0; i < filas; i++) {
            for (int j = 1; j < columnas; j++){
                String values[]=new String[3];
                values[0]=jTable1.getValueAt(i,0).toString();
                values[1]=jTable1.getColumnName(j);
                values[2]=jTable1.getValueAt(i,j).toString();
                transiciones.add(new Transicion(values[0], values[1], values[2]));
            }
            
        }
        Transicion ArrayTransition[]= new Transicion[transiciones.size()];
        for (int i = 0; i < transiciones.size(); i++) {
            ArrayTransition[i] = transiciones.get(i);
            
        }
        dfa=new DFA(getEstados(), getAlfabeto(), getEstadosFinales(),ArrayTransition,getEstadoInicial());
                
        return transiciones;
    }
    
    private String[] getEstadosFinales(){
        return txtEstadosFinales.getText().split(",");
    }
    
    private void printTransiciones(){
        for (Transicion t: getTransiciones()) {
            System.out.println("Estado Actual:"+t.getStartState()+"Arista de Transicion:"+t.getInput()+" Nuevo Estado:"+t.getNewState());
        }
    }
    
    private void evaluarArchivoTexto(){
        TextFile texto=new TextFile(cmbTextFile.getSelectedItem().toString()+".txt");
        BufferedReader br= texto.getContenido();
        String text="";
        try {
            System.out.println("===========================\n    Archivo: "+cmbTextFile.getSelectedItem()+"\n===========================");
            while((text=br.readLine())!=null){
                if(esAceptada(text)){
                    System.out.println(text+" :"+Colores.ANSI_GREEN+ " Aceptada"+Colores.ANSI_RESET);
                }else{
                    System.out.println(text+" :"+Colores.ANSI_RED+" No aceptada"+Colores.ANSI_RESET);
                }
                dfa.reset();
            }
            System.out.println("");
        } catch (IOException  ex) {
            System.err.println("Error al intentar leer archivo ");
        }catch(NullPointerException ex){
            System.err.println("No existe ningun contenido en el archivo leer archivo ");
        }catch(InvalidParameterException ex){
            System.out.print("La cadena "+Colores.ANSI_YELLOW+text+Colores.ANSI_RESET+" contiene un caracter que no existe en el alfabeto");
        }
    
    }
    private boolean esAceptada(String text)throws InvalidParameterException{
        int cont=0;
        if(text.length()==0){
            return dfa.isAccepting();
        }
        try{
            while(dfa.input(String.valueOf(text.charAt(cont)))!=null  && cont<text.length()){
                if(dfa.isAccepting() && ck_contentSubstring.isSelected()){
                    return dfa.isAccepting();
                }
                cont++;
            }
            return dfa.isAccepting();
        }catch(StringIndexOutOfBoundsException e){
            return dfa.isAccepting();
        }
    }
    
    private void evaluarEntrada(){
        try{
            if(esAceptada(txtEntrada.getText())){
                lblMensaje.setText("Aceptada");
                lblMensaje.setForeground(new Color(0,102,51));
            }else{
                lblMensaje.setText("No Aceptada");
                lblMensaje.setForeground(Color.red);
            }
        }catch(InvalidParameterException e){
            lblMensaje.setText("'"+caracterNoExiste(txtEntrada.getText())+"' no exite en el alfabeto");
            lblMensaje.setForeground(Color.BLACK);
            dfa.reset();
            lblMensaje.setVisible(true);
        }
        dfa.reset();
        lblMensaje.setVisible(true);
    }
    
    private void cargarDirectorios(){
        cmbTextFile.removeAllItems();
       if(getFileInDirectorio()!=null){
           
           for(File f:getFileInDirectorio()){
                String nombreArchivo=f.getName().substring(0,f.getName().lastIndexOf("."));
                cmbTextFile.addItem(nombreArchivo);
           }
       }
       cmbTextFile.setSelectedIndex(-1);
    }
    
    private File[] getFileInDirectorio(){
        return new TextFile().getFiles();
    }
    
    private char caracterNoExiste(String cadena){
        String alfabeto="";
        for (String string : getAlfabeto()) {
            alfabeto+=string;
        }
        for (int i = 0; i < cadena.length(); i++) {
            if(!alfabeto.contains(String.valueOf(cadena.charAt(i)))){
                return cadena.charAt(i);
            }
        }    
        return 0;
    }
    
    
   
}
